server:
  port: 8091

spring:
  application:
    name: config-client
    bus:
      env:
        enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh