server:
  port: 8091

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      uri: http://localhost:8888
      name: config-info
      profile: dev
    bus:
      env:
        enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh