server:
  port: 8091

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
#      uri: http://localhost:8888 采用注册中心获取
      name: config-info
      profile: prod
      discovery:
        #从配置中心读取文件
        enabled: true
        #配置中心的servieId，即服务名
        service-id: config-server

    bus:
      env:
        enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh