server:
  port: 8779

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411

eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.0.100
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/