application:
  name: CloudService
  code: CloudService
  adminUser: admin
server:
  port: 8010
#  servlet:
#    context-path: /${application.code}
spring:
  resources:
    static-locations: classpath:/static/
hello:
  enable: true